blank_template = [
             {"badge_name":"cia","code":"CIA", "file_name":"cia-template.png", "is_inverted":False}, 
             {"badge_name":"Meme Warfare","code":"MW", "file_name":"meme-warfare-template.png", "is_inverted":False},
             {"badge_name":"discord","code":"DISCORD", "file_name":"discord-template.png", "is_inverted":False},
             {"badge_name":"nypd","code":"NYPD", "file_name":"nypd-template.png", "is_inverted":False},
             {"badge_name":"cicada","code":"CICADA", "file_name":"cicada-template.png", "is_inverted":False},
             {"badge_name":"ioi","code":"IOI", "file_name":"IOI-template.png", "is_inverted":False},
             {"badge_name":"fbi","code":"FBI", "file_name":"fbi-template.png", "is_inverted":False},
             {"badge_name":"nsa","code":"NSA", "file_name":"nsa-template.png", "is_inverted":False},
             {"badge_name":"gab","code":"GAB", "file_name":"gab-template.png", "is_inverted":False},
             {"badge_name":"dop","code":"DOP", "file_name":"dop-template.png", "is_inverted":False},
             {"badge_name":"shit","code":"SHIT", "file_name":"shit-template.png", "is_inverted":False},
             {"badge_name":"bunker","code":"BUNKER", "file_name":"bunker-template.png", "is_inverted":False},
             {"badge_name":"dprk","code":"DPRK", "file_name":"nk-template.png", "is_inverted":False},
             {"badge_name":"kek","code":"KEK", "file_name": "kek-template.png", "is_inverted":False},
             {"badge_name":"q","code":"Q !ITPb.qbhqo", "file_name":"Q-template.png", "is_inverted":True},
             {"badge_name":"dhs","code":"SpaceX", "file_name":"spacex-template.png", "is_inverted":False},
             {"badge_name":"unsc","code":"UNSC", "file_name": "unsc-template.png", "is_inverted":False},
             {"badge_name":"Anahein Ducks","code":"ANA", "file_name": 'Anaheim Ducks-template.png', "is_inverted":False},
             {"badge_name":"Arizona Coyotes","code":"ARI", "file_name": 'Arizona Coyotes-template.png', "is_inverted":False},
             {"badge_name":"Boston Bruins","code":"BOS", "file_name": 'Boston Bruins-template.png', "is_inverted":False},
             {"badge_name":"Buffalo Sabres","code":"BUF", "file_name": 'Buffalo Sabres-template.png', "is_inverted":False},
             {"badge_name":"","code":"CGY", "file_name": 'Calgary Flames-template.png', "is_inverted":False},
             {"badge_name":"Carolina Hurricanes","code":"CAR", "file_name": 'Carolina Hurricanes-template.png', "is_inverted":False},
             {"badge_name":"Chicago Blackhawks","code":"CHI", "file_name": 'Chicago Blackhawks-template.png', "is_inverted":False},
             {"badge_name":"Colorado Avalanche","code":"COL", "file_name": 'Colorado Avalanche-template.png', "is_inverted":False},
             {"badge_name":"Columbus Blue Jackets","code":"CBJ", "file_name": 'Columbus Blue Jackets-template.png', "is_inverted":False},
             {"badge_name":"Dallas Stars","code":"DAL", "file_name": 'Dallas Stars-template.png', "is_inverted":False},
             {"badge_name":"Detroit Red Wings","code":"DET", "file_name":'Detroit Red Wings-template.png', "is_inverted":False},
             {"badge_name":"Edmonton Oilers","code":"EDM", "file_name":'Edmonton Oilers-template.png', "is_inverted":False},
             {"badge_name":"Florida Panthers","code":"FLA", "file_name": 'Florida Panthers-template.png', "is_inverted":False},
             {"badge_name":"Los Angeles Kings","code":"LAK", "file_name": 'Los Angeles Kings-template.png', "is_inverted":False},
             {"badge_name":"Minnesota Wild","code":"MIN", "file_name": 'Minnesota Wild-template.png', "is_inverted":False},
             {"badge_name":"Montréal Canadiens","code":"MTL", "file_name": 'Montréal Canadiens-template.png', "is_inverted":False},
             {"badge_name":"Nashville Predators","code":"NSH", "file_name": 'Nashville Predators-template.png', "is_inverted":False},
             {"badge_name":"New Jersey Devils","code":"NJD", "file_name": 'New Jersey Devils-template.png', "is_inverted":False},
             {"badge_name":"New York Islanders","code":"NYI", "file_name": 'New York Islanders-template.png', "is_inverted":False},
             {"badge_name":"New York Rangers","code":"NYR", "file_name": 'New York Rangers-template.png', "is_inverted":False},
             {"badge_name":"Ottawa Senators","code":"OTT", "file_name": 'Ottawa Senators-template.png', "is_inverted":False},
             {"badge_name":"Philadelphia Flyers","code":"PHI", "file_name": 'Philadelphia Flyers-template.png', "is_inverted":False},
             {"badge_name":"Pittsburgh Penguins","code":"PIT", "file_name": 'Pittsburgh Penguins-template.png', "is_inverted":False},
             {"badge_name":"San Jose Sharks","code":"SJS", "file_name": 'San Jose Sharks-template.png', "is_inverted":False},
             {"badge_name":"St. Louis Blues","code":"STL", "file_name": 'St. Louis Blues-template.png', "is_inverted":False},
             {"badge_name":"Tampa Bay Lightning","code":"TBL", "file_name": 'Tampa Bay Lightning-template.png', "is_inverted":False},
             {"badge_name":"Toronto Maple Leafs","code":"TOR", "file_name": 'Toronto Maple Leafs-template.png', "is_inverted":False},
             {"badge_name":"Vancouver Canucks","code":"VAN", "file_name": 'Vancouver Canucks-template.png', "is_inverted":False},
             {"badge_name":"Vegas Golden Knights","code":"VGK", "file_name": 'Vegas Golden Knights-template.png', "is_inverted":False},
             {"badge_name":"Washington Capitals","code":"WSH", "file_name":'Washington Capitals-template.png', "is_inverted":False},
             {"badge_name":"Winnipeg Jets","code":"WPG", "file_name": 'Winnipeg Jets-template.png', "is_inverted":False},
             {"badge_name":"Seattle Thunderbirds","code":"STT", "file_name": 'Seattle Thunderbirds-template.png', "is_inverted":False},
             {"badge_name":"unity4j","code":"U4J", "file_name": 'Unity4J-template.png', "is_inverted":False}]