blank_template = {"cia":{"code":"CIA", "loc":"cia-template.png"}, 
             "discord":{"code":"DISCORD", "loc":"discord-template.png"},
             "nypd":{"code":"NYPD", "loc":"nypd-template.png"},
             "cicada":{"code":"CICADA", "loc":"cicada-template.png"},
             "ioi":{"code":"IOI", "loc":"IOI-template.png"},
             "fbi":{"code":"FBI", "loc":"fbi-template.png"},
             "nsa":{"code":"NSA", "loc":"nsa-template.png"},
             "gab":{"code":"GAB", "loc":"gab-template.png"},
             "dop":{"code":"DOP", "loc":"dop-template.png"},
             "shit":{"code":"SHIT", "loc":"shit-template.png"},
             "bunker":{"code":"BUNKER", "loc":"bunker-template.png"},
             "dprk":{"code":"DPRK", "loc":"nk-template.png"},
             "kek":{"code":"KEK", "loc": "kek-template.png"},
             "Q":{"code":"Q !ITPb.qbhqo", "loc":"Q-template.png"},
             "dhs":{"code":"SpaceX", "loc":"spacex-template.png"},
             "unsc":{"code":"UNSC", "loc": "unsc-template.png"},
             'Anaheim Ducks':{"code":"ANA", "loc": 'Anaheim Ducks-template.png'},
             'Arizona Coyotes':{"code":"ARI", "loc": 'Arizona Coyotes-template.png'},
             'Boston Bruins':{"code":"BOS", "loc": 'Boston Bruins-template.png'},
             'Buffalo Sabres':{"code":"BUF", "loc": 'Buffalo Sabres-template.png'},
             'Calgary Flames':{"code":"CGY", "loc": 'Calgary Flames-template.png'},
             'Carolina Hurricanes':{"code":"CAR", "loc": 'Carolina Hurricanes-template.png'},
             'Chicago Blackhawks':{"code":"CHI", "loc": 'Chicago Blackhawks-template.png'},
             'Colorado Avalanche':{"code":"COL", "loc": 'Colorado Avalanche-template.png'},
             'Columbus Blue Jackets':{"code":"CBJ", "loc": 'Columbus Blue Jackets-template.png'},
             'Dallas Stars':{"code":"DAL", "loc": 'Dallas Stars-template.png'},
             'Detroit Red Wings':{"code":"DET", "loc":'Detroit Red Wings-template.png'},
             'Edmonton Oilers':{"code":"EDM", "loc":'Edmonton Oilers-template.png'},
             'Florida Panthers':{"code":"FLA", "loc": 'Florida Panthers-template.png'},
             'Los Angeles Kings':{"code":"LAK", "loc": 'Los Angeles Kings-template.png'},
             'Minnesota Wild':{"code":"MIN", "loc": 'Minnesota Wild-template.png'},
             'Montréal Canadiens':{"code":"MTL", "loc": 'Montréal Canadiens-template.png'},
             'Nashville Predators':{"code":"NSH", "loc": 'Nashville Predators-template.png'},
             'New Jersey Devils':{"code":"NJD", "loc": 'New Jersey Devils-template.png'},
             'New York Islanders':{"code":"NYI", "loc": 'New York Islanders-template.png'},
             'New York Rangers':{"code":"NYR", "loc": 'New York Rangers-template.png'},
             'Ottawa Senators':{"code":"OTT", "loc": 'Ottawa Senators-template.png'},
             'Philadelphia Flyers':{"code":"PHI", "loc": 'Philadelphia Flyers-template.png'},
             'Pittsburgh Penguins':{"code":"PIT", "loc": 'Pittsburgh Penguins-template.png'},
             'San Jose Sharks':{"code":"SJS", "loc": 'San Jose Sharks-template.png'},
             'St. Louis Blues':{"code":"STL", "loc": 'St. Louis Blues-template.png'},
             'Tampa Bay Lightning':{"code":"TBL", "loc": 'Tampa Bay Lightning-template.png'},
             'Toronto Maple Leafs':{"code":"TOR", "loc": 'Toronto Maple Leafs-template.png'},
             'Vancouver Canucks':{"code":"VAN", "loc": 'Vancouver Canucks-template.png'},
             'Vegas Golden Knights':{"code":"VGK", "loc": 'Vegas Golden Knights-template.png'},
             'Washington Capitals':{"code":"WSH", "loc":'Washington Capitals-template.png'},
             'Winnipeg Jets':{"code":"WPG", "loc": 'Winnipeg Jets-template.png'},
             'Seattle Thunderbirds': {"code":"STT", "loc": 'Seattle Thunderbirds-template.png'}}